options:
  logging: CLOUD_LOGGING_ONLY

steps:
- name: 'hashicorp/terraform:light'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      terraform init
      terraform plan
      terraform apply -auto-approve
timeout: 1200s
